services:
  labprobe-mqtt:
    extends:
      file: docker-compose.host.yml
      service: labprobe-mqtt
  router-browser:
    extends:
      file: docker-compose.host.yml
      service: router-browser
  labprobe-hub:
    extends:
      file: docker-compose.host.yml
      service: labprobe-hub
