"""LabProbe Hub entrypoint with direct Ruijie router control enabled."""
from pathlib import Path

import hub
from agent_presence_patch import install_agent_presence_patch
from device_history_patch import install_device_history_patch
from final_stability_patch import install_final_stability_patch
from followup_stability_patch import install_followup_stability_patch
from hub0934_fixes import install_hub0934_fixes
from hub_realtime_ws import install_hub_realtime_ws
from labrelay_sync_patch import install_labrelay_sync_patch
from portmap_persistence_patch import install_portmap_persistence_patch
from router_be72_auth_patch import install_router_be72_auth_patch
from router_be72_sid_wire_patch import install_router_be72_sid_wire_patch
from router_build024_fix import install_router_build024_fix
from router_compat import install_router_rpc_compat
from router_config_sync_patch import install_router_config_sync_patch
from router_control_actor_patch import install_router_control_actor_patch
from router_control_scheduler_patch import install_router_control_scheduler_patch
from router_device_live_sync_patch import install_router_device_live_sync_patch
from router_developer_flow_patch import install_router_developer_flow_patch
from router_fast_watchdog_patch import install_router_fast_watchdog_patch
from router_http_developer_transport_patch import install_router_http_developer_transport_patch
from router_lite_realtime_patch import install_router_lite_realtime_patch
from router_native_features_patch import install_router_native_features_patch
from router_realtime_stability_patch import (
    install_router_realtime_stability_patch,
    install_router_status_localization,
)
from router_relay_credentials_patch import install_router_relay_credentials_patch
from router_rpc_v010 import create_router_blueprint_v010
from router_slow_cache_patch import install_router_slow_cache_patch
from router_task_manager_patch import install_router_task_manager
from router_ws_patch import install_router_ws_patch

HUB_VERSION = "0.9.34"
hub.APP_VERSION = HUB_VERSION
install_router_http_developer_transport_patch()
install_router_developer_flow_patch()
install_router_be72_auth_patch()
install_router_be72_sid_wire_patch()
install_router_native_features_patch()
install_router_ws_patch()
install_router_fast_watchdog_patch()
install_router_realtime_stability_patch()
install_router_build024_fix()
install_router_relay_credentials_patch()
install_router_slow_cache_patch()
install_router_control_scheduler_patch()
install_router_control_actor_patch()
install_router_task_manager(hub)
hub.app.register_blueprint(
    create_router_blueprint_v010(
        check_app_token=hub.check_app_token,
        logger=hub.LOGGER,
        config_dir=Path(hub.CONFIG_DIR),
    )
)
router_sync = install_router_rpc_compat(hub)
install_router_status_localization(hub, router_sync)
router_lite_realtime = install_router_lite_realtime_patch(hub, router_sync)
install_hub_realtime_ws(hub, router_lite_realtime)
install_router_config_sync_patch(hub, hub.ROUTER_TASK_MANAGER.client)
install_agent_presence_patch(hub)
install_device_history_patch(hub)
install_portmap_persistence_patch(hub)
install_router_device_live_sync_patch(hub, hub.ROUTER_TASK_MANAGER.client)
install_followup_stability_patch(hub, router_lite_realtime)
install_final_stability_patch(hub)
install_labrelay_sync_patch(hub)
install_hub0934_fixes(hub)

if __name__ == "__main__":
    raise SystemExit(hub.command_line())
