persistence true
persistence_location /mosquitto/data/
log_dest stdout
log_timestamp true
connection_messages true
log_type error
log_type warning
log_type notice
log_type information

listener 1883 127.0.0.1
protocol mqtt
allow_anonymous false
password_file /mosquitto/config/runtime/passwords

listener 9001 0.0.0.0
protocol websockets
allow_anonymous false
password_file /mosquitto/config/runtime/passwords
