persistence true
persistence_location /mosquitto/data/
log_dest stdout

listener 1883
protocol mqtt
allow_anonymous false
password_file /mosquitto/config/runtime/passwords

listener 9001 0.0.0.0
protocol websockets
allow_anonymous false
password_file /mosquitto/config/runtime/passwords
