#!/bin/sh /etc/rc.common
START=98
STOP=11
USE_PROCD=1

CONF=/etc/labprobe/relay-agent.conf
SCRIPT=/etc/labprobe/labrelay_agent.sh

start_service() {
    procd_open_instance
    procd_set_param command "$SCRIPT" daemon
    procd_set_param respawn 5 5 0
    procd_set_param stdout 1
    procd_set_param stderr 1
    procd_set_param file "$CONF" "$SCRIPT"
    procd_close_instance
}

service_triggers() {
    procd_add_reload_trigger labprobe
}
